* 第一章 入门
** 1.2 Linux 程序设计
   Linux 并不要求可执行文件或脚本文件具有特殊的文件名或扩展名。
   在进行shell程序交互的时候，它在一组指定的目录路径下搜索。搜索的路径存储在shell变量PATH中。
*** 通常包含如下一些存储系统程序的标准路径：
    /bin： 二进制文件目录，用于存放启动系统时用到的程序。
    /usr/bin/: 用户二进制文件目录，用于存放用户使用的标准程序。
    /usr/local/bin: 本地二进制目录，用于存放软件安装的程序。
    可选的操作系统组件和第三方应用程序可能被安装在/opt 目录下，安装程序可以通过用户安装脚本将路径添加到PATH环境变量中。
   
*** 库文件
    库是一组预先编译好的函数集合，这些函数都是按照可重用的原则编写的。
    库文件名总是以lib开头，随后的部分指明这是什么库：
    .a 代表传统的静态函数库。
    .so 代表共享函数库。
**** 共享库
     静态库的一个缺点是，当你同时运行许多应用程序并且它们都使用来自同一个函数时，内存中就会有同一个函数的多份副本，
     而且在程序文件自身中也有多份同样的副本。这将消耗大量的宝贵内存和磁盘空间。
     共享库的链接方式: 
     程序本身不再包含函数代码，而是引用运行时可访问的共享代码，当编译好的程序被装载到内存中执行时，函数引用被解析
     并产生对共享库的调用，如果有必要，共享库才被加载到内存中。

** 常用命令
   1. 在调用C语言编辑器时，可以使用 -I 标志来包含保存在子目录或非标准位置中的头文件。
   2. 用grep命令来搜索包含某些特定定义和函数原型的头文件是很方便的。
   3. -lm 是简写方式，它代表的是标准库目录中名为libm.a 库。-lm的另外一个好处是如果有共享库，编译器
      会自动选择共享库。
   4. -L 标志为编译器增加库的搜索路径。
   5. -c 选项的作用是组织编译器创建一个完整的程序。
   6. ldd 来查看一个程序需要的共享库.
* 第二章 shell程序设计
** 2.1 为什么使用shell 编程
   使用shell进行程序设计的原因之一是，你可以快速，简单的完成编程。
   shell中执行shell程序，通常被称为脚本。
